=head1 NAME

	Asterisk::ParseConfig::Extensions - the Asterisk extensions configs parse and find incorrect rows

=head1 SYNOPSIS

	use Asterisk::ParseConfig::Extensions;
	
	my $exten = Asterisk::ParseConfig::Extensions->new({ 	CONFIG_FILENAME     => 'extensions.conf',
								ASTERISK_PATH       => '/etc/asterisk' });
	$exten->parse({  RECURSIVE  => 'true' });

=head1 DESCRIPTION

	Модуль для парсинга файла extensions.conf и его производных.
	Определяет контексты, инклуды файлов и контекстов.
	При необходимости, разбирает все включенные файлы рекурсивно.

	При обнаружении некорректных строк выводит предупреждения.
	При обнаружении инклудов несуществующих файлов выводит ошибку.

=head1 METHODS

=head2 parse()

	...

=head1 AUTHOR

	Alexander Ruzhnikov (ruzhnikov85@gmail.com)

=head1 COPYRIGHT AND LICENSE

	Copyright (C) 2013 by Alexander Ruzhnikov (ruzhnikov85@gmail.com)

	This module is free software.  You can redistribute it and/or modify it under the terms of the Artistic License 2.0.

	This program is distributed in the hope that it will be useful, but without any warranty; without even the implied 
	warranty of merchantability or fitness for a particular purpose.

=cut
